name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Swift toolchain
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "6.0.1"

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build Swift package
        run: swift build --product box

      - name: Run Swift tests
        run: swift test --parallel
