name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swift-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Swift dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            binutils \
            clang \
            git \
            gnupg2 \
            libc6-dev \
            libatomic1 \
            libcurl4-openssl-dev \
            libedit2 \
            libgcc-11-dev \
            libicu70 \
            libncurses5 \
            libncursesw5 \
            libpython3.10 \
            libsqlite3-0 \
            libstdc++6 \
            libxml2 \
            libz3-dev \
            tzdata \
            unzip \
            zlib1g-dev \
            pkg-config

      - name: Install Swift 6.2 toolchain
        env:
          SWIFT_VERSION: "6.2"
          UBUNTU_VERSION: "22.04"
        run: |
          ARCHIVE="swift-${SWIFT_VERSION}-RELEASE-ubuntu${UBUNTU_VERSION}"
          curl -fL "https://download.swift.org/swift-${SWIFT_VERSION}-release/ubuntu$(echo ${UBUNTU_VERSION} | tr -d '.')/swift-${SWIFT_VERSION}-RELEASE/${ARCHIVE}.tar.gz" -o swift.tar.gz
          tar -xzf swift.tar.gz
          sudo mv "${ARCHIVE}" "/opt/swift-${SWIFT_VERSION}"
          sudo ln -sf /usr/bin/ld "/opt/swift-${SWIFT_VERSION}/usr/bin/ld"
          echo "/opt/swift-${SWIFT_VERSION}/usr/bin" >> "$GITHUB_PATH"
          {
            echo "SWIFT_HOME=/opt/swift-${SWIFT_VERSION}"
            echo "LD_LIBRARY_PATH=/opt/swift-${SWIFT_VERSION}/usr/lib/swift/linux:\$LD_LIBRARY_PATH"
            echo "LIBRARY_PATH=/opt/swift-${SWIFT_VERSION}/usr/lib/swift/linux:\$LIBRARY_PATH"
            echo "PATH=/opt/swift-${SWIFT_VERSION}/usr/bin:\$PATH"
          } >> "$GITHUB_ENV"

      - name: Resolve dependencies
        run: swift package resolve

      - name: Build Swift package
        run: swift build --product box

      - name: Run Swift tests
        run: swift test --parallel
